r"""A small deterministic TOML emitter — the byte contract the two inputs-template projections share.

A projected inputs template is TOML text as well as a JSON object, and the two projections — this
one and the TypeScript twin in the `mthds` npm package — must produce the *same bytes*, the
`# concept: …` comment lines included. Neither language's TOML library can be handed that job:
`smol-toml` emits no comments at all, and a library's layout choices are its own to change in a
patch release, on its own schedule, in one language and not the other. So the layout is written out
here, in the few dozen lines it takes, and mirrored line for line on the other side;
`tests/fixtures/protocol/inputs_template/` is the corpus that holds the two to it.

Two layouts, because a template has two shapes:

- **The table layout** (`render_table_layout`) — what the explicit `{concept, content}` shape takes.
  Every top-level value in it is a table, so the plain sectioned layout is both valid and readable.
- **The inline layout** (`render_inline_layout`) — what the compact shape takes. A compact template
  interleaves bare top-level scalars with structured values, so every value stays at the top level
  as an inline table: authored order survives, a trailing scalar is not swallowed into the section
  above it, and each key can carry its own `# concept: …` line.

The rules the table layout follows, which is the part a library would otherwise be deciding:

- A table states its scalar members first, in authored order, then its table members, also in
  authored order. TOML cannot interleave a section with the keys of its parent, so the split itself
  is forced; keeping each half in authored order is the choice.
- A table whose members are *all* tables states no header of its own — its children carry the whole
  dotted path (`[page_in.content.text_and_images]`). An empty table is not one of those: it has no
  child to carry its path, so it states its header and stands alone.
- A non-empty list of tables is an array of tables: one `[[dotted.path]]` header per element, and an
  element always states its header, even when every one of its own members is a table.
- Exactly one blank line before every header, and none before the first line of the document.

TOML has no null. A `None` is written as an empty string rather than dropped, so the key stays
visible to whoever fills the template in — an omitted key reads as a field the method never declared.

The blank-line rule is applied uniformly here, and `tomlkit` — which the corpus generator in
`pipelex` still renders through — does not apply it uniformly. It omits the blank line before an
array-of-tables that is the first member of its container (`{"items": [{"a": 1}], "label": "x"}` →
`label = "x"\n[[items]]`), and before the first table-ish member of an array-of-tables element
(`{"outer": [{"inner": [{"a": 1}]}]}` → `[[outer]]\n[[outer.inner]]`), because its trivia
bookkeeping records the newline on a wrapper its own array renderer never reads. It also reorders a
mapping's members when that mapping is an element of a list, sorting mapping-valued members last.
The committed corpus exercises none of those shapes, so the two agree on every byte of it today —
but a bundle added to the corpus could reach them, and the regenerated bytes would then carry the
inconsistency and fail both projections at once. The fix is for the generator to render through this
contract rather than through a TOML library; `L-260831-4031a7` tracks it in `pipelex`.
"""

import string
from typing import Any, cast

_BARE_KEY_CHARACTERS = frozenset(string.ascii_letters + string.digits + "-_")

# The escapes a TOML basic string spells compactly; every other control character takes `\uXXXX`.
_COMPACT_ESCAPES = {
    "\b": "\\b",
    "\t": "\\t",
    "\n": "\\n",
    "\f": "\\f",
    "\r": "\\r",
    '"': '\\"',
    "\\": "\\\\",
}
_CONTROL_CHARACTERS = frozenset(chr(code_point) for code_point in range(0x20)) | {chr(0x7F)}

_TRUE = "true"
_FALSE = "false"


class TomlEmissionError(ValueError):
    """A value the emitter has no TOML spelling for reached it.

    A `ValueError` because that is what it is — the template handed in is not renderable — and the
    projection builds every value it emits, so this is a programming error rather than bad input.
    """


def render_table_layout(*, template: dict[str, Any]) -> str:
    """Render a template whose values are all tables, as sectioned TOML.

    Args:
        template: The template, one entry per declared input slot, in authored order.

    Returns:
        The TOML text, ending in exactly one newline; the empty string for an empty template.
    """
    lines: list[str] = []
    _emit_members(table=_substitute_nulls(value=template), path=(), lines=lines)
    return _join(lines=lines)


def render_inline_layout(*, template: dict[str, Any], comments: dict[str, str]) -> str:
    """Render a template as top-level keys carrying inline values, each optionally commented.

    Args:
        template: The template, one entry per declared input slot, in authored order.
        comments: Per-key comment text, without its leading `# `. A key with no entry takes no
            comment line.

    Returns:
        The TOML text, ending in exactly one newline; the empty string for an empty template.
    """
    lines: list[str] = []
    for key, value in _substitute_nulls(value=template).items():
        comment_text = comments.get(key)
        if comment_text:
            lines.append(f"# {comment_text}")
        lines.append(f"{_render_key(key=key)} = {_render_inline_value(value=value)}")
    return _join(lines=lines)


def _join(*, lines: list[str]) -> str:
    """One newline after every line, and nothing at all for a document with no lines."""
    if not lines:
        return ""
    return "\n".join(lines) + "\n"


def _substitute_nulls(*, value: Any) -> Any:
    """Replace every `None` with an empty string, recursively — TOML has no null."""
    if value is None:
        return ""
    if isinstance(value, dict):
        return {key: _substitute_nulls(value=member) for key, member in cast("dict[str, Any]", value).items()}
    if isinstance(value, list):
        return [_substitute_nulls(value=element) for element in cast("list[Any]", value)]
    return value


def _is_table_value(*, value: Any) -> bool:
    """Whether a value takes a section of its own rather than a `key = value` line.

    A mapping always does. A list does exactly when it is a non-empty list of mappings — an array of
    tables; a list of scalars, a mixed list and an empty list are all inline arrays.
    """
    if isinstance(value, dict):
        return True
    if isinstance(value, list):
        elements = cast("list[Any]", value)
        return bool(elements) and all(isinstance(element, dict) for element in elements)
    return False


def _is_super_table(*, table: dict[str, Any]) -> bool:
    """Whether a table states no header of its own, leaving its children to carry the dotted path.

    Non-empty and nothing but tables inside. An empty table is deliberately not one: it has no child
    to state the path, so a header is the only thing that puts it in the document at all.
    """
    if not table:
        return False
    return all(_is_table_value(value=value) for value in table.values())


def _emit_members(*, table: dict[str, Any], path: tuple[str, ...], lines: list[str]) -> None:
    """Emit one table's body: its scalar members first, in authored order, then its table members."""
    table_members: dict[str, Any] = {}
    for key, value in table.items():
        if _is_table_value(value=value):
            table_members[key] = value
        else:
            lines.append(f"{_render_key(key=key)} = {_render_inline_value(value=value)}")
    for key, value in table_members.items():
        member_path = (*path, key)
        if isinstance(value, dict):
            _emit_table(table=cast("dict[str, Any]", value), path=member_path, lines=lines, is_array_element=False)
        else:
            for element in cast("list[Any]", value):
                _emit_table(table=cast("dict[str, Any]", element), path=member_path, lines=lines, is_array_element=True)


def _emit_table(*, table: dict[str, Any], path: tuple[str, ...], lines: list[str], is_array_element: bool) -> None:
    """Emit one table, with its header unless it is a super table, then its body."""
    if is_array_element or not _is_super_table(table=table):
        if lines:
            lines.append("")
        open_marker, close_marker = ("[[", "]]") if is_array_element else ("[", "]")
        lines.append(f"{open_marker}{_render_path(path=path)}{close_marker}")
    _emit_members(table=table, path=path, lines=lines)


def _render_path(*, path: tuple[str, ...]) -> str:
    """The dotted header path, each segment spelled the way a key is."""
    return ".".join(_render_key(key=segment) for segment in path)


def _render_key(*, key: str) -> str:
    """A bare key where TOML allows one, a quoted key otherwise — a dotted input name included."""
    if key and all(character in _BARE_KEY_CHARACTERS for character in key):
        return key
    return _render_string(text=key)


def _render_inline_value(*, value: Any) -> str:
    """One value on a single line: an inline table, an inline array, or a scalar."""
    if isinstance(value, dict):
        members = cast("dict[str, Any]", value)
        rendered = ", ".join(f"{_render_key(key=key)} = {_render_inline_value(value=member)}" for key, member in members.items())
        return f"{{{rendered}}}"
    if isinstance(value, list):
        rendered = ", ".join(_render_inline_value(value=element) for element in cast("list[Any]", value))
        return f"[{rendered}]"
    return _render_scalar(value=value)


def _render_scalar(*, value: Any) -> str:
    """One scalar, spelled as TOML spells it. `bool` is tested first: in Python it is also an `int`."""
    if isinstance(value, bool):
        return _TRUE if value else _FALSE
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, str):
        return _render_string(text=value)
    msg = f"No TOML spelling for a value of type '{type(value).__name__}'"
    raise TomlEmissionError(msg)


def _render_string(*, text: str) -> str:
    r"""A basic string: the compact escapes where there is one, `\uXXXX` for any other control character."""
    escaped: list[str] = []
    for character in text:
        compact = _COMPACT_ESCAPES.get(character)
        if compact is not None:
            escaped.append(compact)
        elif character in _CONTROL_CHARACTERS:
            escaped.append(f"\\u{ord(character):04x}")
        else:
            escaped.append(character)
    body = "".join(escaped)
    return f'"{body}"'
